"""Core Loop Troop functionality."""

from .adr_loader import ADRLoader
from .context_hydrator import (
    ContextBudgetExceededError,
    ContextHydrator,
    WorkspaceViolationError,
)
from .github_client import (
    GitHubClient,
    GitHubIssue,
    GitHubIssueComment,
    GitHubIssueEvent,
    GitHubLabel,
    GitHubPullRequest,
    InMemoryETagStore,
    PollResponse,
)
from .llm_client import LLMClient, PreparedLLMClient
from .schemas import (
    ADRDocument,
    ADRStatus,
    ArchitectPlan,
    ChecklistItem,
    CodePatch,
    DispatchDecision,
    DispatchLabelAction,
    EventType,
    FeaturePlan,
    FileChange,
    LabelActionType,
    ReviewComment,
    ReviewVerdict,
    ReviewVerdictType,
    SubIssue,
    TargetExecutionProfile,
    WorkerTier,
)
from .workspace_manager import TemplateValidationError, WorkspaceManager, WorkspaceUpdateError

__all__ = [
    "ADRDocument",
    "ADRLoader",
    "ADRStatus",
    "ContextBudgetExceededError",
    "ContextHydrator",
    "GitHubClient",
    "GitHubIssue",
    "GitHubIssueComment",
    "GitHubIssueEvent",
    "GitHubLabel",
    "GitHubPullRequest",
    "InMemoryETagStore",
    "LLMClient",
    "PollResponse",
    "PreparedLLMClient",
    "ArchitectPlan",
    "ChecklistItem",
    "CodePatch",
    "DispatchDecision",
    "DispatchLabelAction",
    "EventType",
    "FeaturePlan",
    "FileChange",
    "LabelActionType",
    "ReviewComment",
    "ReviewVerdict",
    "ReviewVerdictType",
    "SubIssue",
    "TargetExecutionProfile",
    "WorkerTier",
    "WorkspaceManager",
    "WorkspaceViolationError",
    "TemplateValidationError",
    "WorkspaceUpdateError",
]
